### ISSUE TITLE
netpeak.xml missing

### ISSUE THREAD

**Issue by mhedevk** [glenpp/cacti-netpeakmond#1]
I tried to configure cacti-netpeakmond, but the netpeak.xml is missing. The link on your website is dead too. I tried to reconstruct it by the things I found in your project, but I still have some issues.

Maybe you can check it, or add your original file.

TIA

  Martin
[netpeak.xml.zip](https://github.com/glenpp/cacti-netpeakmond/files/681150/netpeak.xml.zip)

**Comment by glenpp** [comment]
Thanks for point it out - I'd just not pushed the commit with those files. Should all be correct now, and I've updated URLs to https (http redirects anyway)
